# Generated by Django 3.1.1 on 2020-09-27 17:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvtomatizaciyaPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Страница автоматизация',
                'verbose_name_plural': 'Страница автоматизация',
            },
        ),
        migrations.AlterField(
            model_name='block1item',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block1items', to='staticPages.homepage'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featureitems', to='staticPages.homepage'),
        ),
        migrations.AlterField(
            model_name='manufactory',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactoryitems', to='staticPages.homepage'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partneritems', to='staticPages.homepage'),
        ),
    ]
