# Generated by Django 3.1.1 on 2020-09-27 18:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0002_auto_20200927_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProizvodsvoPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Страница производство',
                'verbose_name_plural': 'Страница производство',
            },
        ),
    ]
