# Generated by Django 3.1.1 on 2020-09-27 18:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0003_proizvodsvopage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Картинка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание ')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='manufactory',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое страницы'),
        ),
    ]
