# Generated by Django 3.1.1 on 2020-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0004_auto_20200927_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата изготовления'),
        ),
    ]
