# Generated by Django 3.1.1 on 2020-09-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0005_project_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTypePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Направления компании', max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(default='Компания создает системы АСУТП и электроснабжения для различных технологических установок.<br>Для получения детальной информации свяжитесь с нами.<br>Наши решения поставляются на заводы ПАО «НК «Роснефть», ПАО "Газпром", ГУП «Водоканал Санкт-Петербурга» и другие.<br>Ниже представлены основные объекты для создания систем АСУТП и электроснабжения.', verbose_name='Описание ')),
            ],
            options={
                'verbose_name': 'Страница направления',
                'verbose_name_plural': 'Страница направления',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Картинка')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wortypes', to='staticPages.worktypepage')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
    ]
