# Generated by Django 3.1.1 on 2020-09-28 06:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticPages', '0006_worktype_worktypepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страница о нас',
            },
        ),
    ]
