# Generated by Django 3.1.1 on 2020-09-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделия',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название товара')),
                ('option_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название товара')),
                ('name_lower', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item/', verbose_name='Картинка')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название страницы')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Описание страницы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU')),
                ('itemOption1Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название опции1')),
                ('itemOption1Value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение опции1')),
                ('itemOption2Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название опции2')),
                ('itemOption2Value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение опции2')),
                ('itemAddOption1Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название доп. опции1')),
                ('itemAddOption1Value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение доп. опции1')),
                ('itemAddOption2Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название доп. опции2')),
                ('itemAddOption2Value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение доп. опции2')),
                ('itemAddOption3Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название доп. опции3')),
                ('itemAddOption3Value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение доп. опции3')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать товар ?')),
                ('is_present', models.BooleanField(db_index=True, default=True, verbose_name='Товар в наличии ?')),
                ('is_new', models.BooleanField(db_index=True, default=False, verbose_name='Товар новинка ?')),
                ('buys', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.manufactor', verbose_name='Производитель')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.series', verbose_name='Серия')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.type', verbose_name='Тип изделия')),
            ],
        ),
    ]
