# Generated by Django 3.1.1 on 2020-11-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория')),
                ('name_lower', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подкатегория')),
                ('name_lower', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Относится к ')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption1Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption1Value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption2Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption2Value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption3Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemAddOption3Value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemOption1Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemOption1Value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemOption2Name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemOption2Value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='option_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='defence',
            field=models.IntegerField(default=0, verbose_name='Степень защиты, IP'),
        ),
        migrations.AddField(
            model_name='item',
            name='faz_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр: Количество фаз'),
        ),
        migrations.AddField(
            model_name='item',
            name='inputs',
            field=models.IntegerField(default=0, verbose_name='Кол-во вводов'),
        ),
        migrations.AddField(
            model_name='item',
            name='kabel_input',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кабельный ввод'),
        ),
        migrations.AddField(
            model_name='item',
            name='life_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок эксплуатации'),
        ),
        migrations.AddField(
            model_name='item',
            name='napryag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр: Напряжение, В'),
        ),
        migrations.AddField(
            model_name='item',
            name='nominal_tok',
            field=models.IntegerField(default=0, verbose_name='Номинальный ток'),
        ),
        migrations.AddField(
            model_name='item',
            name='parametr_check',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контроль параметров'),
        ),
        migrations.AddField(
            model_name='item',
            name='power',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр: Мощность, кВт'),
        ),
        migrations.AddField(
            model_name='item',
            name='size_shelter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер шкафа ШхГхВ'),
        ),
        migrations.AddField(
            model_name='item',
            name='tok_str',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр: Сила тока, А'),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Гарантия'),
        ),
        migrations.AddField(
            model_name='item',
            name='work_temperature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Температурный режим'),
        ),
        migrations.AddField(
            model_name='item',
            name='work_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='item',
            name='series',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Параметр: Серия'),
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.subcategory', verbose_name='Относится к '),
        ),
    ]
