# Generated by Django 3.1.1 on 2020-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201103_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='engine_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во двигателей'),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_power',
            field=models.IntegerField(default=0, verbose_name='Мощность двигателя, кВт'),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Способ запуска двигателя'),
        ),
        migrations.AddField(
            model_name='item',
            name='engine_tok',
            field=models.IntegerField(default=0, verbose_name='Ток двигателя'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_avr',
            field=models.BooleanField(default=False, verbose_name='Наличие АВР'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_counters',
            field=models.BooleanField(default=False, verbose_name='Наличие АВР'),
        ),
        migrations.AddField(
            model_name='item',
            name='number_zadvigek',
            field=models.IntegerField(default=0, verbose_name='Кол-во задвижек'),
        ),
        migrations.AddField(
            model_name='item',
            name='setup_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Способ установки'),
        ),
    ]
