# Generated by Django 3.1.1 on 2020-11-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201103_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='privod_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип привода'),
        ),
        migrations.AddField(
            model_name='item',
            name='pump_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во насосов'),
        ),
        migrations.AddField(
            model_name='item',
            name='pump_power',
            field=models.IntegerField(default=0, verbose_name='Мощность насоса, кВт'),
        ),
    ]
