# Generated by Django 3.1.1 on 2020-11-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20201103_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='defence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Степень защиты, IP'),
        ),
    ]
