# Generated by Django 3.1.1 on 2020-11-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20201103_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='Относится к '),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_counters',
            field=models.BooleanField(default=False, verbose_name='Наличие счетчиков'),
        ),
    ]
